class AddAutoGeneratedInput < ActiveRecord::Migration[5.0]
  def up 
    add_column :inputs, :auto_generated, :boolean, default: false, null: false
  end

  def down 
    remove_column :inputs, :auto_generated
  end
end
